### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by z11h**

### CODE REVIEW

**Comment by gyzerok** [comment]
Hi Zakaria, thanks for your PR!

Are you sure that no changes to the code required after updating to the major release?

**Comment by amilajack** [comment]
The tests fail for this PR. The current stable release for this build is also failing. We should look into why the tests arent passing first.

**Comment by amilajack** [comment]
Just checked the reason. The builds are failing because there are no tests to run. Adding some tests would be a start.

**Comment by gyzerok** [comment]
Closing PR now. Feel free to create new after all necessary checks.

**Pull request closed without merging**
